Description: Cert-Manager Installation Stack for HyperPod Operators
Parameters:
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
    Description: Prefix to be used for all resources created by this template.
  EKSClusterName:
    Type: String
    Description: The name of the EKS cluster where cert-manager will be installed.
  HyperpodCliGithubRepoUrl:
    Type: String
    Default: https://github.com/aws/sagemaker-hyperpod-cli.git
    Description: GitHub repository URL for HyperPod CLI containing Helm charts
  CustomResourceS3Bucket:
    Type: String
    Default: aws-sagemaker-hyperpod-cluster-setup-us-east-2-prod
    Description: The name of the S3 bucket containing the custom resource.
  LayerS3Key:
    Type: String
    Default: resources/artifacts/cert-manager-lambda-layer.zip
    Description: The S3 key for the lambda layer zip file.
  FunctionS3Key:
    Type: String
    Default: resources/artifacts/cert-manager-lambda-function.zip
    Description: The S3 key for the lambda function zip file.
Resources:
  CertManagerCustomResourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - eks:DescribeCluster
                Resource:
                  Fn::Sub: arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/${EKSClusterName}
          PolicyName:
            Fn::Sub: ${ResourceNamePrefix}-CertManager-EKSAccess
    Metadata:
      aws:cdk:path: CertManagerCfnTemplate/CertManagerCustomResourceRole
  CertManagerCustomResourceAccessEntry:
    Type: AWS::EKS::AccessEntry
    Properties:
      AccessPolicies:
        - AccessScope:
            Type: cluster
          PolicyArn: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
      ClusterName:
        Ref: EKSClusterName
      PrincipalArn:
        Fn::GetAtt:
          - CertManagerCustomResourceRole
          - Arn
    Metadata:
      aws:cdk:path: CertManagerCfnTemplate/CertManagerCustomResourceAccessEntry
  CertManagerCustomResourceLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11
        - python3.12
      Content:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key:
          Ref: LayerS3Key
      Description: Lambda Layer for kubectl and helm tools for cert-manager installation
      LayerName:
        Fn::Sub: ${ResourceNamePrefix}-cert-manager-layer
    Metadata:
      aws:cdk:path: CertManagerCfnTemplate/CertManagerCustomResourceLayer
  CertManagerCustomResourceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key:
          Ref: FunctionS3Key
      Environment:
        Variables:
          EKS_CLUSTER_NAME:
            Ref: EKSClusterName
          HYPERPOD_CLI_GITHUB_REPO_URL:
            Ref: HyperpodCliGithubRepoUrl
          HYPERPOD_CLI_GITHUB_REPO_REVISION: 0ae955c8f6af3153829ecc0c59d3bd499cac91e9
          PATH: /opt/python/bin:/var/lang/bin:/usr/local/bin:/usr/bin/:/bin
          GIT_EXEC_PATH: /opt/python/libexec/git-core
          KUBECONFIG: /tmp/.kube/config
          LD_LIBRARY_PATH: /opt/python/lib
      FunctionName:
        Fn::Sub: ${ResourceNamePrefix}-cert-manager-installer
      Handler: lambda_function.lambda_handler
      Layers:
        - Ref: CertManagerCustomResourceLayer
      MemorySize: 1024
      Role:
        Fn::GetAtt:
          - CertManagerCustomResourceRole
          - Arn
      Runtime: python3.12
      Timeout: 900
    DependsOn:
      - CertManagerCustomResourceAccessEntry
    Metadata:
      aws:cdk:path: CertManagerCfnTemplate/CertManagerCustomResourceFunction
  CertManagerCustomResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CertManagerCustomResourceFunction
          - Arn
    DependsOn:
      - CertManagerCustomResourceFunction
    Metadata:
      aws:cdk:path: CertManagerCfnTemplate/CertManagerCustomResource
Outputs:
  CertManagerInstallationComplete:
    Description: Indicates cert-manager installation is complete
    Value: CertManagerInstallationComplete
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-CertManagerInstallationComplete
  CertManagerCustomResourceArn:
    Description: ARN of the cert-manager custom resource
    Value:
      Ref: CertManagerCustomResource
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-CertManagerCustomResourceArn
  CertManagerLambdaArn:
    Description: ARN of the cert-manager Lambda function
    Value:
      Fn::GetAtt:
        - CertManagerCustomResourceFunction
        - Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-CertManagerLambdaArn
