Description: Cert-Manager Installation Stack for HyperPod Operators
Parameters:
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
    Description: Prefix to be used for all resources created by this template.
  EKSClusterName:
    Type: String
    Description: The name of the EKS cluster where cert-manager will be installed.
  CertManagerAddonVersion:
    Type: String
    Default: v1.18.2-eksbuild.2
    Description: Version of the cert-manager EKS add-on to install
Resources:
  CertManagerAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: cert-manager
      AddonVersion:
        Ref: CertManagerAddonVersion
      ClusterName:
        Ref: EKSClusterName
      ConfigurationValues: >-
        {"replicaCount":1,"tolerations":[{"operator":"Exists","effect":"NoSchedule"},{"operator":"Exists","effect":"NoExecute"},{"operator":"Exists","effect":"PreferNoSchedule"}],"webhook":{"replicaCount":1,"tolerations":[{"operator":"Exists","effect":"NoSchedule"},{"operator":"Exists","effect":"NoExecute"},{"operator":"Exists","effect":"PreferNoSchedule"}]},"cainjector":{"replicaCount":1,"tolerations":[{"operator":"Exists","effect":"NoSchedule"},{"operator":"Exists","effect":"NoExecute"},{"operator":"Exists","effect":"PreferNoSchedule"}]}}
      ResolveConflicts: OVERWRITE
    Metadata:
      aws:cdk:path: CertManagerCfnTemplate/CertManagerAddon
Outputs:
  CertManagerAddonArn:
    Description: ARN of the cert-manager EKS Add-on
    Value:
      Fn::GetAtt:
        - CertManagerAddon
        - Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-CertManagerAddonArn
