Description: HyperPod training operator Main Stack
Parameters:
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
    Description: Prefix to be used for all resources created by this template.
  EKSClusterName:
    Type: String
    Default: eks
    Description: The name of the EKS cluster.
  Stage:
    Type: String
    Default: gamma
    AllowedValues:
      - gamma
      - prod
    Description: Deployment stage (gamma, prod)
  CustomBucketName:
    Type: String
    Default: ''
    Description: Custom S3 bucket name for templates. If provided, will override the default bucket. Leave empty to use default.
Conditions:
  CustomBucketCondition:
    Fn::Not:
      - Fn::Equals:
          - Ref: CustomBucketName
          - ''
Resources:
  HptoIamRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::If:
          - CustomBucketCondition
          - Fn::Sub: https://${CustomBucketName}.s3.${AWS::Region}.amazonaws.com/templates/hpto-iam-role-template.yaml
          - Fn::Sub: >-
              https://aws-sagemaker-hyperpod-cluster-setup-${AWS::Region}-${Stage}.s3.${AWS::Region}.amazonaws.com/templates/hpto-iam-role-template.yaml
      Parameters:
        ResourceNamePrefix:
          Ref: ResourceNamePrefix
    Metadata:
      aws:cdk:path: HptoMainStackCfnTemplate/HptoIamRoleStack
  HptoEksAddonStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::If:
          - CustomBucketCondition
          - Fn::Sub: https://${CustomBucketName}.s3.${AWS::Region}.amazonaws.com/templates/hpto-eks-addon-template.yaml
          - Fn::Sub: >-
              https://aws-sagemaker-hyperpod-cluster-setup-${AWS::Region}-${Stage}.s3.${AWS::Region}.amazonaws.com/templates/hpto-eks-addon-template.yaml
      Parameters:
        ResourceNamePrefix:
          Ref: ResourceNamePrefix
        EKSClusterName:
          Ref: EKSClusterName
        HptoIamRoleArn:
          Fn::GetAtt:
            - HptoIamRoleStack
            - Outputs.HptoIamRoleArn
    DependsOn:
      - HptoIamRoleStack
    Metadata:
      aws:cdk:path: HptoMainStackCfnTemplate/HptoEksAddonStack
Outputs:
  HPTOIAMRoleArn:
    Description: ARN of the HPTO IAM role
    Value:
      Fn::GetAtt:
        - HptoIamRoleStack
        - Outputs.HptoIamRoleArn
  HPTOIAMRoleName:
    Description: Name of the HPTO IAM role
    Value:
      Fn::GetAtt:
        - HptoIamRoleStack
        - Outputs.HptoIamRoleName
