Description: HP Training Operator EKS Add-on Stack
Parameters:
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
    Description: Prefix to be used for all resources created by this template.
  EKSClusterName:
    Type: String
    Default: eks
    Description: The name of the EKS cluster.
  HptoIamRoleArn:
    Type: String
    Description: ARN of the HPTO IAM Role.
  CustomResourceS3Bucket:
    Type: String
    Default: aws-sagemaker-hyperpod-cluster-setup-us-east-2-prod
    Description: The name of the S3 bucket containing the custom resource.
  LayerS3Key:
    Type: String
    Default: resources/artifacts/hpto-addon-lambda-layer.zip
    Description: The S3 key for the lambda layer zip file.
  FunctionS3Key:
    Type: String
    Default: resources/artifacts/hpto-addon-lambda-function.zip
    Description: The S3 key for the lambda function zip file.
Resources:
  HptoPodIdentityAssociation:
    Type: AWS::EKS::PodIdentityAssociation
    Properties:
      ClusterName:
        Ref: EKSClusterName
      Namespace: aws-hyperpod
      RoleArn:
        Ref: HptoIamRoleArn
      ServiceAccount: hp-training-operator-controller-manager
    Metadata:
      aws:cdk:path: HptoEksAddonCfnTemplate/HptoPodIdentityAssociation
  HptoAddonCustomResourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - eks:DescribeCluster
                  - eks:DescribeAddon
                  - eks:CreateAddon
                  - eks:DeleteAddon
                  - eks:UpdateAddon
                Resource:
                  - Fn::Sub: arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/${EKSClusterName}
                  - Fn::Sub: >-
                      arn:aws:eks:${AWS::Region}:${AWS::AccountId}:addon/${EKSClusterName}/amazon-sagemaker-hyperpod-training-operator/*
          PolicyName:
            Fn::Sub: ${ResourceNamePrefix}-HPTO-Addon-Access
    Metadata:
      aws:cdk:path: HptoEksAddonCfnTemplate/HptoAddonCustomResourceRole
  HptoAddonCustomResourceAccessEntry:
    Type: AWS::EKS::AccessEntry
    Properties:
      AccessPolicies:
        - AccessScope:
            Type: cluster
          PolicyArn: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
      ClusterName:
        Ref: EKSClusterName
      PrincipalArn:
        Fn::GetAtt:
          - HptoAddonCustomResourceRole
          - Arn
    Metadata:
      aws:cdk:path: HptoEksAddonCfnTemplate/HptoAddonCustomResourceAccessEntry
  HptoAddonCustomResourceLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11
        - python3.12
      Content:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key:
          Ref: LayerS3Key
      Description: Lambda Layer for kubectl tools for HPTO add-on installation
      LayerName:
        Fn::Sub: ${ResourceNamePrefix}-hpto-addon-layer
    Metadata:
      aws:cdk:path: HptoEksAddonCfnTemplate/HptoAddonCustomResourceLayer
  HptoAddonCustomResourceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key:
          Ref: FunctionS3Key
      Environment:
        Variables:
          EKS_CLUSTER_NAME:
            Ref: EKSClusterName
          PATH: /opt/python/bin:/var/lang/bin:/usr/local/bin:/usr/bin/:/bin
          KUBECONFIG: /tmp/.kube/config
          LD_LIBRARY_PATH: /opt/python/lib
      FunctionName:
        Fn::Sub: ${ResourceNamePrefix}-hptofunc
      Handler: lambda_function.lambda_handler
      Layers:
        - Ref: HptoAddonCustomResourceLayer
      MemorySize: 1024
      Role:
        Fn::GetAtt:
          - HptoAddonCustomResourceRole
          - Arn
      Runtime: python3.12
      Timeout: 900
    DependsOn:
      - HptoAddonCustomResourceAccessEntry
    Metadata:
      aws:cdk:path: HptoEksAddonCfnTemplate/HptoAddonCustomResourceFunction
  HptoAddonCustomResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - HptoAddonCustomResourceFunction
          - Arn
    DependsOn:
      - HptoAddonCustomResourceFunction
      - HptoPodIdentityAssociation
    Metadata:
      aws:cdk:path: HptoEksAddonCfnTemplate/HptoAddonCustomResource
Outputs:
  HptoPodIdentityAssociationArn:
    Description: ARN of the HPTO Pod Identity Association
    Value:
      Fn::GetAtt:
        - HptoPodIdentityAssociation
        - AssociationArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-HptoPodIdentityAssociationArn
  HptoAddonStatus:
    Description: Status of HPTO add-on installation
    Value:
      Fn::GetAtt:
        - HptoAddonCustomResource
        - AddonStatus
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-HptoAddonStatus
  HptoAddonCustomResourceArn:
    Description: ARN of the HPTO add-on custom resource
    Value:
      Ref: HptoAddonCustomResource
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-HptoAddonCustomResourceArn
