Description: RIG Endpoint Stack (Lambda and SQS)
Parameters:
  VpcId:
    Type: String
    Default: vpc-1234567890abcdef0
    Description: The ID of the VPC you wish to use to create RIG endpoints
  PrivateSubnetIds:
    Type: CommaDelimitedList
    Default: subnet-1234567890abcdef0
    Description: The IDs of your private subnets.
  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: sg-1234567890abcdef0
    Description: The IDs of security groups to associate with the VPC endpoints.
  HasGatedAccess:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Whether to create SQS endpoint for gated access.
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
    Description: Prefix to be used for all resources created by this template.
Conditions:
  CreateSqsEndpoint:
    Fn::Equals:
      - Ref: HasGatedAccess
      - 'true'
Resources:
  LambdaEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        Ref: SecurityGroupIds
      ServiceName:
        Fn::Join:
          - ''
          - - com.amazonaws.
            - Ref: AWS::Region
            - .lambda
      SubnetIds:
        Ref: PrivateSubnetIds
      Tags:
        - Key: aws-sagemaker-hyperpod-prerequiste
          Value:
            Fn::Sub: ${ResourceNamePrefix}-lambda-vpc-endpoint
        - Key: Name
          Value:
            Fn::Sub: ${ResourceNamePrefix}-lambda-vpc-endpoint
      VpcEndpointType: Interface
      VpcId:
        Ref: VpcId
    Metadata:
      aws:cdk:path: RigEndpointCfnTemplate/LambdaEndpoint
  SqsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        Ref: SecurityGroupIds
      ServiceName:
        Fn::Join:
          - ''
          - - com.amazonaws.
            - Ref: AWS::Region
            - .sqs
      SubnetIds:
        Ref: PrivateSubnetIds
      Tags:
        - Key: aws-sagemaker-hyperpod-prerequiste
          Value:
            Fn::Sub: ${ResourceNamePrefix}-sqs-vpc-endpoint
        - Key: Name
          Value:
            Fn::Sub: ${ResourceNamePrefix}-sqs-vpc-endpoint
      VpcEndpointType: Interface
      VpcId:
        Ref: VpcId
    Metadata:
      aws:cdk:path: RigEndpointCfnTemplate/SqsEndpoint
    Condition: CreateSqsEndpoint
