Description: SageMaker Spaces Addon Stack for HyperPod

Parameters:
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
    Description: Prefix for resource names
  EKSClusterName:
    Type: String
    Description: Name of the EKS cluster

Resources:
  # IAM Role for Spaces Controller (Pod Identity)
  SpacesControllerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${ResourceNamePrefix}-spaces-controller
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: pods.eks.amazonaws.com
            Action:
              - sts:AssumeRole
              - sts:TagSession
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerSpacesControllerPolicy

  # IAM Role for Spaces Router/Auth Middleware (Pod Identity)
  SpacesRouterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${ResourceNamePrefix}-spaces-router
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: pods.eks.amazonaws.com
            Action:
              - sts:AssumeRole
              - sts:TagSession
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerSpacesRouterPolicy

  # SageMaker Spaces EKS Addon
  SpacesAddon:
    Type: AWS::EKS::Addon
    DependsOn:
      - SpacesControllerRole
      - SpacesRouterRole
    Properties:
      ClusterName:
        Ref: EKSClusterName
      AddonName: amazon-sagemaker-spaces
      ResolveConflicts: OVERWRITE
      PodIdentityAssociations:
        - ServiceAccount: jupyter-k8s-controller-manager
          Namespace: jupyter-k8s-system
          RoleArn:
            Fn::GetAtt:
              - SpacesControllerRole
              - Arn
        - ServiceAccount: jupyter-k8s-authmiddleware
          Namespace: jupyter-k8s-system
          RoleArn:
            Fn::GetAtt:
              - SpacesRouterRole
              - Arn

Outputs:
  SpacesControllerRoleArn:
    Description: ARN of the Spaces Controller IAM Role
    Value:
      Fn::GetAtt:
        - SpacesControllerRole
        - Arn
  SpacesRouterRoleArn:
    Description: ARN of the Spaces Router IAM Role
    Value:
      Fn::GetAtt:
        - SpacesRouterRole
        - Arn
  SpacesAddonName:
    Description: Name of the Spaces addon
    Value: amazon-sagemaker-spaces
