Description: SageMaker Spaces WorkspaceTemplates with nodeSelector for node placement

Parameters:
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
  EKSClusterName:
    Type: String
  CustomResourceS3Bucket:
    Type: String
    Default: aws-sagemaker-hyperpod-cluster-setup-us-east-2-prod
  LayerS3Key:
    Type: String
    Default: resources/artifacts/fsx-lambda-layer.zip
    Description: The S3 key for the lambda layer zip file
  FunctionS3Key:
    Type: String
    Default: resources/artifacts/workspace-templates-lambda-function.zip
  UserNamespaces:
    Type: String
    Default: kubeflow
    Description: Unused - kept for main-stack compatibility

Resources:
  WorkspaceTemplatesRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${ResourceNamePrefix}-workspace-templates-role
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: eks:DescribeCluster
                Resource:
                  Fn::Sub: arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/${EKSClusterName}
          PolicyName: EKSAccess

  WorkspaceTemplatesAccessEntry:
    Type: AWS::EKS::AccessEntry
    Properties:
      AccessPolicies:
        - AccessScope:
            Type: cluster
          PolicyArn: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
      ClusterName:
        Ref: EKSClusterName
      PrincipalArn:
        Fn::GetAtt:
          - WorkspaceTemplatesRole
          - Arn

  WorkspaceTemplatesLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11
        - python3.12
      Content:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key:
          Ref: LayerS3Key
      Description: Lambda Layer for kubectl and aws-iam-authenticator
      LayerName:
        Fn::Sub: ${ResourceNamePrefix}-workspace-templates-layer

  WorkspaceTemplatesFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key:
          Ref: FunctionS3Key
      Environment:
        Variables:
          CLUSTER_NAME:
            Ref: EKSClusterName
          PATH: /opt/python/bin:/var/lang/bin:/usr/local/bin:/usr/bin/:/bin
          KUBECONFIG: /tmp/.kube/config
          LD_LIBRARY_PATH: /opt/python/lib
      FunctionName:
        Fn::Sub: ${ResourceNamePrefix}-workspace-templates
      Handler: lambda_function.lambda_handler
      Layers:
        - Ref: WorkspaceTemplatesLayer
      Role:
        Fn::GetAtt:
          - WorkspaceTemplatesRole
          - Arn
      Runtime: python3.12
      Timeout: 300
    DependsOn:
      - WorkspaceTemplatesAccessEntry

  WorkspaceTemplatesCustomResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - WorkspaceTemplatesFunction
          - Arn

Outputs:
  JupyterCPUTemplateName:
    Description: Name of the JupyterLab CPU WorkspaceTemplate
    Value: jupyter-cpu-template
  JupyterGPUTemplateName:
    Description: Name of the JupyterLab GPU WorkspaceTemplate
    Value: jupyter-gpu-template
  CodeEditorCPUTemplateName:
    Description: Name of the Code Editor CPU WorkspaceTemplate
    Value: code-editor-cpu-template
  CodeEditorGPUTemplateName:
    Description: Name of the Code Editor GPU WorkspaceTemplate
    Value: code-editor-gpu-template
